language: scala
scala:
- 2.11.8
jdk:
- oraclejdk8
script: sbt ++${TRAVIS_SCALA_VERSION} amm/test $(if [[ "${TRAVIS_PULL_REQUEST}"
  == "false" && "${TRAVIS_BRANCH}" == "master" ]]; then echo "published/publish";
  fi)
branches:
  only:
  - master
env:
  global:
    secure: bRTmSL4sBHWWsYZIWknPlNZxokHY08ortiIodBFAGvkteGIBHuRBniSIvuOysg1QlG1ggZXilsXbNvyzj0L21uPNDWm3y90IDny7j9GBLaYfiIJ3SPanjnU6bmruUPWgxR5e2owzClLQedizocZAIh9e35M0zCmLtcTbr/g/2QI=
cache:
  directories:
  - $HOME/.coursier
  - $HOME/.ivy2/cache
  - $HOME/.sbt
